
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Oct 19 2025 17:36:18 IST (Oct 19 2025 12:06:18 UTC)

// Verification Directory fv/Serial_multiplier16bit 

module Serial_multiplier16bit(Serial_multin1, Serial_multin2, clk, rst,
     Serial_multout);
  input [15:0] Serial_multin1, Serial_multin2;
  input clk, rst;
  output [31:0] Serial_multout;
  wire [15:0] Serial_multin1, Serial_multin2;
  wire clk, rst;
  wire [31:0] Serial_multout;
  wire [3:0] count;
  wire [31:0] Parproduct_sum;
  wire add_33_42_n_2, add_33_42_n_3, add_33_42_n_4, add_33_42_n_5,
       add_33_42_n_6, add_33_42_n_7, add_33_42_n_8, add_33_42_n_9;
  wire add_33_42_n_10, add_33_42_n_11, add_33_42_n_12, add_33_42_n_13,
       add_33_42_n_14, add_33_42_n_15, add_33_42_n_16, add_33_42_n_17;
  wire add_33_42_n_18, add_33_42_n_19, add_33_42_n_20, add_33_42_n_21,
       add_33_42_n_23, add_33_42_n_24, add_33_42_n_25, add_33_42_n_27;
  wire add_33_42_n_29, add_33_42_n_30, add_33_42_n_32, add_33_42_n_33,
       add_33_42_n_34, add_33_42_n_36, add_33_42_n_37, add_33_42_n_39;
  wire add_33_42_n_40, add_33_42_n_42, add_33_42_n_43, add_33_42_n_45,
       add_33_42_n_46, add_33_42_n_48, add_33_42_n_49, add_33_42_n_51;
  wire add_33_42_n_53, add_33_42_n_55, add_33_42_n_57, add_33_42_n_59,
       add_33_42_n_61, add_33_42_n_63, add_33_42_n_65, add_33_42_n_67;
  wire add_33_42_n_69, add_33_42_n_71, add_33_42_n_73, add_33_42_n_75,
       add_33_42_n_77, add_33_42_n_79, add_33_42_n_81, add_33_42_n_83;
  wire add_33_42_n_85, add_33_42_n_87, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_47, n_48, n_49, n_50;
  wire n_52, n_54, n_55, n_56, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_106, n_107, n_110, n_116, n_119, n_120, n_124;
  wire n_126, n_130, n_131, n_133, n_135, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_201, n_202, n_203, n_204;
  wire n_205, n_206, n_207, n_208, n_209, n_210, n_211, n_212;
  wire n_213, n_214, n_215, n_216, n_217, n_218, n_219, n_220;
  wire n_221, n_222, n_223, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_231, n_265, n_266, n_267, n_268, n_269;
  wire n_270, n_271, n_272, n_273, n_274, n_275, n_276, n_277;
  wire n_278, n_279, n_280, n_281, n_282, n_283, n_284, n_285;
  wire n_286, n_287, n_288, n_289, n_290, n_291, n_292, n_293;
  wire n_294, n_295, n_296, n_298, n_299, n_300, n_301, n_302;
  wire n_303, n_304, n_305, n_306, n_307, n_308, n_309, n_310;
  wire n_311;
  DFFQXL \Serial_multout_reg[0] (.CK (clk), .D (n_100), .Q
       (Serial_multout[0]));
  DFFQXL \Serial_multout_reg[1] (.CK (clk), .D (n_66), .Q
       (Serial_multout[1]));
  DFFQXL \Serial_multout_reg[2] (.CK (clk), .D (n_69), .Q
       (Serial_multout[2]));
  DFFQXL \Serial_multout_reg[3] (.CK (clk), .D (n_60), .Q
       (Serial_multout[3]));
  DFFQXL \Serial_multout_reg[4] (.CK (clk), .D (n_98), .Q
       (Serial_multout[4]));
  DFFQXL \Serial_multout_reg[5] (.CK (clk), .D (n_82), .Q
       (Serial_multout[5]));
  DFFQXL \Serial_multout_reg[6] (.CK (clk), .D (n_99), .Q
       (Serial_multout[6]));
  DFFQXL \Serial_multout_reg[7] (.CK (clk), .D (n_68), .Q
       (Serial_multout[7]));
  DFFQXL \Serial_multout_reg[8] (.CK (clk), .D (n_86), .Q
       (Serial_multout[8]));
  DFFQXL \Serial_multout_reg[9] (.CK (clk), .D (n_95), .Q
       (Serial_multout[9]));
  DFFQXL \Serial_multout_reg[10] (.CK (clk), .D (n_97), .Q
       (Serial_multout[10]));
  DFFQXL \Serial_multout_reg[11] (.CK (clk), .D (n_90), .Q
       (Serial_multout[11]));
  DFFQXL \Serial_multout_reg[12] (.CK (clk), .D (n_89), .Q
       (Serial_multout[12]));
  DFFQXL \Serial_multout_reg[13] (.CK (clk), .D (n_91), .Q
       (Serial_multout[13]));
  DFFQXL \Serial_multout_reg[14] (.CK (clk), .D (n_102), .Q
       (Serial_multout[14]));
  DFFQXL \Serial_multout_reg[15] (.CK (clk), .D (n_85), .Q
       (Serial_multout[15]));
  DFFQXL \Serial_multout_reg[16] (.CK (clk), .D (n_65), .Q
       (Serial_multout[16]));
  DFFQXL \Serial_multout_reg[17] (.CK (clk), .D (n_81), .Q
       (Serial_multout[17]));
  DFFQXL \Serial_multout_reg[18] (.CK (clk), .D (n_94), .Q
       (Serial_multout[18]));
  DFFQXL \Serial_multout_reg[19] (.CK (clk), .D (n_101), .Q
       (Serial_multout[19]));
  DFFQXL \Serial_multout_reg[20] (.CK (clk), .D (n_92), .Q
       (Serial_multout[20]));
  DFFQXL \Serial_multout_reg[21] (.CK (clk), .D (n_83), .Q
       (Serial_multout[21]));
  DFFQXL \Serial_multout_reg[22] (.CK (clk), .D (n_96), .Q
       (Serial_multout[22]));
  DFFQXL \Serial_multout_reg[23] (.CK (clk), .D (n_61), .Q
       (Serial_multout[23]));
  DFFQXL \Serial_multout_reg[24] (.CK (clk), .D (n_93), .Q
       (Serial_multout[24]));
  DFFQXL \Serial_multout_reg[25] (.CK (clk), .D (n_64), .Q
       (Serial_multout[25]));
  DFFQXL \Serial_multout_reg[26] (.CK (clk), .D (n_63), .Q
       (Serial_multout[26]));
  DFFQXL \Serial_multout_reg[27] (.CK (clk), .D (n_67), .Q
       (Serial_multout[27]));
  DFFQXL \Serial_multout_reg[28] (.CK (clk), .D (n_84), .Q
       (Serial_multout[28]));
  DFFQXL \Serial_multout_reg[29] (.CK (clk), .D (n_88), .Q
       (Serial_multout[29]));
  DFFQXL \Serial_multout_reg[30] (.CK (clk), .D (n_62), .Q
       (Serial_multout[30]));
  DFFQXL \Serial_multout_reg[31] (.CK (clk), .D (n_87), .Q
       (Serial_multout[31]));
  OAI22X1 g3563__2398(.A0 (n_52), .A1 (n_188), .B0 (n_198), .B1
       (n_163), .Y (n_221));
  MXI2XL g3564__5107(.A (n_191), .B (n_151), .S0 (count[3]), .Y
       (n_209));
  MXI2XL g3565__6260(.A (n_184), .B (n_189), .S0 (count[3]), .Y
       (n_214));
  OAI22X1 g3566__4319(.A0 (count[3]), .A1 (n_182), .B0 (n_199), .B1
       (n_176), .Y (n_212));
  OAI22X1 g3567__8428(.A0 (count[3]), .A1 (n_181), .B0 (n_199), .B1
       (n_175), .Y (n_211));
  MXI2XL g3568__5526(.A (n_188), .B (n_192), .S0 (count[3]), .Y
       (n_213));
  MXI2XL g3569__6783(.A (n_180), .B (n_162), .S0 (count[3]), .Y
       (n_210));
  OAI22X1 g3570__3680(.A0 (count[3]), .A1 (n_187), .B0 (n_52), .B1
       (n_190), .Y (n_216));
  MX2X1 g3571__1617(.A (n_186), .B (n_156), .S0 (n_52), .Y (n_223));
  OAI22X1 g3572__2802(.A0 (n_52), .A1 (n_184), .B0 (count[3]), .B1
       (n_160), .Y (n_222));
  OAI22X1 g3573__1705(.A0 (count[3]), .A1 (n_185), .B0 (n_52), .B1
       (n_195), .Y (n_215));
  OAI22X1 g3574__5122(.A0 (n_52), .A1 (n_182), .B0 (n_198), .B1
       (n_173), .Y (n_220));
  OAI22X1 g3575__8246(.A0 (n_52), .A1 (n_191), .B0 (count[3]), .B1
       (n_183), .Y (n_217));
  OAI22X1 g3576__7098(.A0 (n_52), .A1 (n_181), .B0 (count[3]), .B1
       (n_193), .Y (n_219));
  OAI22X1 g3577__6131(.A0 (n_52), .A1 (n_180), .B0 (count[3]), .B1
       (n_194), .Y (n_218));
  NOR2XL g3578__1881(.A (count[3]), .B (n_195), .Y (n_207));
  NOR2XL g3579__5115(.A (count[3]), .B (n_190), .Y (n_208));
  NOR2XL g3580__7482(.A (count[3]), .B (n_189), .Y (n_206));
  NOR2XL g3581__4733(.A (n_52), .B (n_183), .Y (n_225));
  NOR2XL g3582__6161(.A (n_52), .B (n_193), .Y (n_227));
  NOR2XL g3583__9315(.A (n_52), .B (n_194), .Y (n_226));
  NOR2XL g3584__9945(.A (n_52), .B (n_187), .Y (n_224));
  NOR2XL g3585__2883(.A (count[3]), .B (n_192), .Y (n_205));
  AOI22X1 g3586__2346(.A0 (n_56), .A1 (n_164), .B0 (count[2]), .B1
       (n_174), .Y (n_195));
  AOI22X1 g3587__1666(.A0 (count[2]), .A1 (n_178), .B0 (n_80), .B1
       (n_142), .Y (n_194));
  AOI22X1 g3588__7410(.A0 (count[2]), .A1 (n_179), .B0 (n_80), .B1
       (n_139), .Y (n_193));
  AOI21X1 g3589__6417(.A0 (n_56), .A1 (n_177), .B0 (n_152), .Y (n_192));
  MXI2XL g3590__5477(.A (n_168), .B (n_177), .S0 (count[2]), .Y
       (n_191));
  MX2X1 g3591__2398(.A (n_165), .B (n_176), .S0 (count[2]), .Y (n_190));
  AOI21X1 g3592__5107(.A0 (n_56), .A1 (n_172), .B0 (n_161), .Y (n_189));
  INVXL g3593(.A (n_185), .Y (n_186));
  AOI22X1 g3594__6260(.A0 (n_56), .A1 (n_166), .B0 (count[2]), .B1
       (n_168), .Y (n_188));
  MX2X1 g3595__4319(.A (n_173), .B (n_171), .S0 (count[2]), .Y (n_187));
  AOI22X1 g3596__8428(.A0 (n_56), .A1 (n_179), .B0 (count[2]), .B1
       (n_170), .Y (n_185));
  AOI22X1 g3597__5526(.A0 (n_56), .A1 (n_178), .B0 (count[2]), .B1
       (n_169), .Y (n_184));
  MX2X1 g3598__6783(.A (n_163), .B (n_167), .S0 (count[2]), .Y (n_183));
  MX2X1 g3599__3680(.A (n_171), .B (n_165), .S0 (count[2]), .Y (n_182));
  AOI22X1 g3600__1617(.A0 (n_56), .A1 (n_170), .B0 (count[2]), .B1
       (n_164), .Y (n_181));
  AOI22X1 g3601__2802(.A0 (n_56), .A1 (n_169), .B0 (count[2]), .B1
       (n_172), .Y (n_180));
  NOR2XL g3602__1705(.A (n_41), .B (n_176), .Y (n_204));
  NOR2XL g3603__5122(.A (n_41), .B (n_175), .Y (n_203));
  NOR2XL g3604__8246(.A (n_73), .B (n_163), .Y (n_229));
  NOR2XL g3605__7098(.A (n_73), .B (n_173), .Y (n_228));
  INVX1 g3606(.A (n_174), .Y (n_175));
  NOR2XL g3607__6131(.A (n_52), .B (n_160), .Y (n_230));
  NOR2XL g3608__1881(.A (count[3]), .B (n_162), .Y (n_202));
  MXI2XL g3609__5115(.A (n_143), .B (n_155), .S0 (count[1]), .Y
       (n_179));
  MXI2XL g3610__7482(.A (n_158), .B (n_154), .S0 (count[1]), .Y
       (n_178));
  OAI22X1 g3611__4733(.A0 (count[1]), .A1 (n_144), .B0 (n_54), .B1
       (n_157), .Y (n_177));
  MX2X1 g3612__6161(.A (n_150), .B (n_153), .S0 (count[1]), .Y (n_176));
  MXI2XL g3613__9315(.A (n_138), .B (n_157), .S0 (n_54), .Y (n_174));
  MX2X1 g3614__9945(.A (n_141), .B (n_158), .S0 (count[1]), .Y (n_173));
  INVXL g3615(.A (n_166), .Y (n_167));
  OAI22X1 g3616__2883(.A0 (count[1]), .A1 (n_145), .B0 (n_54), .B1
       (n_150), .Y (n_172));
  MX2X1 g3617__2346(.A (n_154), .B (n_146), .S0 (count[1]), .Y (n_171));
  OAI22X1 g3618__1666(.A0 (count[1]), .A1 (n_159), .B0 (n_54), .B1
       (n_149), .Y (n_170));
  OAI22X1 g3619__7410(.A0 (count[1]), .A1 (n_146), .B0 (n_54), .B1
       (n_148), .Y (n_169));
  OAI22X1 g3620__6417(.A0 (count[1]), .A1 (n_149), .B0 (n_54), .B1
       (n_147), .Y (n_168));
  OAI22X1 g3621__5477(.A0 (count[1]), .A1 (n_155), .B0 (n_54), .B1
       (n_159), .Y (n_166));
  MX2X1 g3622__2398(.A (n_148), .B (n_145), .S0 (count[1]), .Y (n_165));
  OAI22X1 g3623__5107(.A0 (count[1]), .A1 (n_147), .B0 (n_54), .B1
       (n_144), .Y (n_164));
  MX2X1 g3624__6260(.A (n_143), .B (n_140), .S0 (n_54), .Y (n_163));
  NOR2XL g3625__4319(.A (n_77), .B (n_153), .Y (n_161));
  NAND2BX1 g3626__8428(.AN (n_153), .B (n_78), .Y (n_162));
  AND2X1 g3627__5526(.A (count[3]), .B (n_156), .Y (n_231));
  NOR3BXL g3628__6783(.AN (n_78), .B (count[3]), .C (n_138), .Y
       (n_201));
  NAND2XL g3629__3680(.A (n_79), .B (n_142), .Y (n_160));
  NOR2XL g3630__1617(.A (n_77), .B (n_138), .Y (n_152));
  AOI22X1 g3631__2802(.A0 (Serial_multin1[10]), .A1 (n_40), .B0
       (Serial_multin1[9]), .B1 (n_137), .Y (n_159));
  NAND2BXL g3632__1705(.AN (n_138), .B (n_78), .Y (n_151));
  AOI22X1 g3633__5122(.A0 (Serial_multin1[13]), .A1 (n_40), .B0
       (Serial_multin1[12]), .B1 (n_137), .Y (n_158));
  AOI22X1 g3634__8246(.A0 (Serial_multin1[2]), .A1 (n_40), .B0
       (Serial_multin1[1]), .B1 (n_137), .Y (n_157));
  NOR2BXL g3635__7098(.AN (n_79), .B (n_140), .Y (n_156));
  AOI22X1 g3636__6131(.A0 (Serial_multin1[12]), .A1 (n_40), .B0
       (Serial_multin1[11]), .B1 (n_137), .Y (n_155));
  AOI22X1 g3637__1881(.A0 (Serial_multin1[11]), .A1 (n_40), .B0
       (Serial_multin1[10]), .B1 (n_137), .Y (n_154));
  AOI22X1 g3638__5115(.A0 (Serial_multin1[1]), .A1 (n_40), .B0
       (Serial_multin1[0]), .B1 (n_137), .Y (n_153));
  INVX1 g3639(.A (n_141), .Y (n_142));
  AOI22X1 g3640__7482(.A0 (Serial_multin1[3]), .A1 (n_40), .B0
       (Serial_multin1[2]), .B1 (n_137), .Y (n_150));
  AOI22X1 g3641__4733(.A0 (Serial_multin1[8]), .A1 (n_40), .B0
       (Serial_multin1[7]), .B1 (n_137), .Y (n_149));
  AOI22X1 g3642__6161(.A0 (Serial_multin1[7]), .A1 (n_40), .B0
       (Serial_multin1[6]), .B1 (n_137), .Y (n_148));
  AOI22X1 g3643__9315(.A0 (Serial_multin1[6]), .A1 (n_40), .B0
       (Serial_multin1[5]), .B1 (n_137), .Y (n_147));
  AOI22X1 g3644__9945(.A0 (Serial_multin1[9]), .A1 (n_40), .B0
       (Serial_multin1[8]), .B1 (n_137), .Y (n_146));
  AOI22X1 g3645__2883(.A0 (Serial_multin1[5]), .A1 (n_40), .B0
       (Serial_multin1[4]), .B1 (n_137), .Y (n_145));
  AOI22X1 g3646__2346(.A0 (Serial_multin1[4]), .A1 (n_40), .B0
       (Serial_multin1[3]), .B1 (n_137), .Y (n_144));
  AOI22X1 g3647__1666(.A0 (Serial_multin1[14]), .A1 (n_40), .B0
       (Serial_multin1[13]), .B1 (n_137), .Y (n_143));
  AOI22X1 g3648__7410(.A0 (Serial_multin1[15]), .A1 (n_40), .B0
       (Serial_multin1[14]), .B1 (n_137), .Y (n_141));
  INVXL g3649(.A (n_140), .Y (n_139));
  NAND2XL g3650__6417(.A (Serial_multin1[15]), .B (n_137), .Y (n_140));
  NAND2XL g3651__5477(.A (Serial_multin1[0]), .B (n_40), .Y (n_138));
  NOR2X2 g3652__2398(.A (n_55), .B (n_298), .Y (n_137));
  NAND2X2 g3655__6260(.A (n_130), .B (n_131), .Y (n_135));
  NOR2X2 g3657__8428(.A (n_302), .B (n_124), .Y (n_133));
  NOR2X1 g3659__6783(.A (n_299), .B (n_126), .Y (n_131));
  NOR2X2 g3660__3680(.A (n_301), .B (n_311), .Y (n_130));
  NAND2X1 g3664__5122(.A (n_116), .B (n_307), .Y (n_126));
  NAND2X2 g3666__7098(.A (n_120), .B (n_305), .Y (n_124));
  NAND3X1 g3672__7482(.A (n_76), .B (n_71), .C (Serial_multin2[4]), .Y
       (n_120));
  NAND2X2 g3673__4733(.A (n_110), .B (Serial_multin2[7]), .Y (n_119));
  NAND3X1 g3677__9945(.A (n_76), .B (n_58), .C (Serial_multin2[0]), .Y
       (n_116));
  NOR2XL g3716__5477(.A (n_74), .B (n_198), .Y (n_110));
  NOR2XL g3729__6260(.A (n_74), .B (n_199), .Y (n_107));
  NOR2XL g3730__4319(.A (n_73), .B (n_197), .Y (n_106));
  NOR2BX1 g3738__3680(.AN (Parproduct_sum[14]), .B (rst), .Y (n_102));
  NOR2BX1 g3739__1617(.AN (Parproduct_sum[19]), .B (rst), .Y (n_101));
  NOR2BX1 g3740__2802(.AN (Parproduct_sum[0]), .B (rst), .Y (n_100));
  NOR2BX1 g3741__1705(.AN (Parproduct_sum[6]), .B (rst), .Y (n_99));
  NOR2BX1 g3742__5122(.AN (Parproduct_sum[4]), .B (rst), .Y (n_98));
  NOR2BX1 g3743__8246(.AN (Parproduct_sum[10]), .B (rst), .Y (n_97));
  NOR2BX1 g3744__7098(.AN (Parproduct_sum[22]), .B (rst), .Y (n_96));
  NOR2BX1 g3745__6131(.AN (Parproduct_sum[9]), .B (rst), .Y (n_95));
  NOR2BX1 g3746__1881(.AN (Parproduct_sum[18]), .B (rst), .Y (n_94));
  NOR2BX1 g3747__5115(.AN (Parproduct_sum[24]), .B (rst), .Y (n_93));
  NOR2BX1 g3748__7482(.AN (Parproduct_sum[20]), .B (rst), .Y (n_92));
  NOR2BX1 g3749__4733(.AN (Parproduct_sum[13]), .B (rst), .Y (n_91));
  NOR2BX1 g3750__6161(.AN (Parproduct_sum[11]), .B (rst), .Y (n_90));
  NOR2BX1 g3751__9315(.AN (Parproduct_sum[12]), .B (rst), .Y (n_89));
  NOR2BX1 g3752__9945(.AN (Parproduct_sum[29]), .B (rst), .Y (n_88));
  NOR2BX1 g3753__2883(.AN (Parproduct_sum[31]), .B (rst), .Y (n_87));
  NOR2BX1 g3754__2346(.AN (Parproduct_sum[8]), .B (rst), .Y (n_86));
  NOR2BX1 g3755__1666(.AN (Parproduct_sum[15]), .B (rst), .Y (n_85));
  NOR2BX1 g3756__7410(.AN (Parproduct_sum[28]), .B (rst), .Y (n_84));
  NOR2BX1 g3757__6417(.AN (Parproduct_sum[21]), .B (rst), .Y (n_83));
  NOR2BX1 g3758__5477(.AN (Parproduct_sum[5]), .B (rst), .Y (n_82));
  NOR2BX1 g3759__2398(.AN (Parproduct_sum[17]), .B (rst), .Y (n_81));
  CLKINVX1 g3760(.A (n_75), .Y (n_197));
  CLKINVX1 g3763(.A (n_74), .Y (n_59));
  CLKINVX1 g3764(.A (n_73), .Y (n_72));
  CLKINVX1 g3767(.A (n_41), .Y (n_58));
  CLKINVX1 g3768(.A (n_198), .Y (n_71));
  CLKINVX1 g3769(.A (n_199), .Y (n_70));
  NOR2BX1 g3770__5107(.AN (Parproduct_sum[2]), .B (rst), .Y (n_69));
  NOR2BX1 g3771__6260(.AN (Parproduct_sum[7]), .B (rst), .Y (n_68));
  NOR2BX1 g3772__4319(.AN (Parproduct_sum[27]), .B (rst), .Y (n_67));
  NOR2BX1 g3773__8428(.AN (Parproduct_sum[1]), .B (rst), .Y (n_66));
  NOR2BX1 g3774__5526(.AN (Parproduct_sum[16]), .B (rst), .Y (n_65));
  NOR2BX1 g3775__6783(.AN (Parproduct_sum[25]), .B (rst), .Y (n_64));
  NOR2BX1 g3776__3680(.AN (Parproduct_sum[26]), .B (rst), .Y (n_63));
  NOR2BX1 g3777__1617(.AN (Parproduct_sum[30]), .B (rst), .Y (n_62));
  NOR2BX1 g3778__2802(.AN (Parproduct_sum[23]), .B (rst), .Y (n_61));
  NOR2BX1 g3779__1705(.AN (Parproduct_sum[3]), .B (rst), .Y (n_60));
  NOR2XL g3780__5122(.A (count[2]), .B (n_54), .Y (n_80));
  NOR2XL g3781__8246(.A (n_56), .B (n_54), .Y (n_79));
  NOR2XL g3782__7098(.A (count[2]), .B (count[1]), .Y (n_78));
  NAND2XL g3783__6131(.A (count[2]), .B (n_54), .Y (n_77));
  AND2X1 g3784__1881(.A (n_55), .B (n_54), .Y (n_76));
  NOR2XL g3786__5115(.A (count[1]), .B (n_55), .Y (n_75));
  NAND2XL g3787__7482(.A (count[1]), .B (count[0]), .Y (n_74));
  NAND2XL g3788__4733(.A (count[2]), .B (count[3]), .Y (n_73));
  INVX1 g3817(.A (count[2]), .Y (n_56));
  CLKINVX1 g3823(.A (count[0]), .Y (n_55));
  INVX1 g3859(.A (count[1]), .Y (n_54));
  NOR2XL g2__6161(.A (n_196), .B (n_41), .Y (n_50));
  NOR2XL g3911__9315(.A (n_196), .B (n_199), .Y (n_49));
  NOR2XL g3912__9945(.A (n_196), .B (n_198), .Y (n_48));
  NOR2XL g3913__2883(.A (n_73), .B (n_196), .Y (n_47));
  NAND2BX1 g3919__2398(.AN (count[2]), .B (count[3]), .Y (n_199));
  NAND2BX1 g3920__5107(.AN (count[2]), .B (n_52), .Y (n_41));
  NOR2BX2 g3921__6260(.AN (n_55), .B (n_298), .Y (n_40));
  NAND2BX1 g3922__4319(.AN (count[0]), .B (count[1]), .Y (n_196));
  NAND2BX1 g3923__8428(.AN (count[3]), .B (count[2]), .Y (n_198));
  DFFQX1 \count_reg[2] (.CK (clk), .D (n_38), .Q (count[2]));
  NOR2XL g1743__5526(.A (n_37), .B (rst), .Y (n_39));
  DFFQX1 \count_reg[1] (.CK (clk), .D (n_35), .Q (count[1]));
  NOR2XL g1745__6783(.A (n_34), .B (rst), .Y (n_38));
  AOI21X1 g1746__3680(.A0 (count[3]), .A1 (n_74), .B0 (n_36), .Y
       (n_37));
  DFFQX1 \Parproduct_sum_reg[1] (.CK (clk), .D (n_29), .Q
       (Parproduct_sum[1]));
  DFFQX1 \Parproduct_sum_reg[25] (.CK (clk), .D (n_3), .Q
       (Parproduct_sum[25]));
  DFFQX1 \Parproduct_sum_reg[27] (.CK (clk), .D (n_31), .Q
       (Parproduct_sum[27]));
  DFFQX1 \Parproduct_sum_reg[28] (.CK (clk), .D (n_30), .Q
       (Parproduct_sum[28]));
  DFFQX1 \Parproduct_sum_reg[26] (.CK (clk), .D (n_32), .Q
       (Parproduct_sum[26]));
  DFFQX1 \Parproduct_sum_reg[30] (.CK (clk), .D (n_28), .Q
       (Parproduct_sum[30]));
  DFFQX1 \Parproduct_sum_reg[29] (.CK (clk), .D (n_33), .Q
       (Parproduct_sum[29]));
  DFFQX1 \Parproduct_sum_reg[31] (.CK (clk), .D (n_27), .Q
       (Parproduct_sum[31]));
  DFFQX1 \Parproduct_sum_reg[0] (.CK (clk), .D (n_21), .Q
       (Parproduct_sum[0]));
  DFFQX1 \Parproduct_sum_reg[9] (.CK (clk), .D (n_16), .Q
       (Parproduct_sum[9]));
  DFFQX1 \Parproduct_sum_reg[2] (.CK (clk), .D (n_24), .Q
       (Parproduct_sum[2]));
  DFFQX1 \Parproduct_sum_reg[3] (.CK (clk), .D (n_23), .Q
       (Parproduct_sum[3]));
  DFFQX1 \Parproduct_sum_reg[4] (.CK (clk), .D (n_22), .Q
       (Parproduct_sum[4]));
  DFFQX1 \Parproduct_sum_reg[5] (.CK (clk), .D (n_20), .Q
       (Parproduct_sum[5]));
  DFFQX1 \Parproduct_sum_reg[6] (.CK (clk), .D (n_19), .Q
       (Parproduct_sum[6]));
  DFFQX1 \Parproduct_sum_reg[7] (.CK (clk), .D (n_18), .Q
       (Parproduct_sum[7]));
  DFFQX1 \Parproduct_sum_reg[8] (.CK (clk), .D (n_17), .Q
       (Parproduct_sum[8]));
  DFFQX1 \count_reg[0] (.CK (clk), .D (n_26), .Q (count[0]));
  DFFQX1 \Parproduct_sum_reg[19] (.CK (clk), .D (n_5), .Q
       (Parproduct_sum[19]));
  DFFQX1 \Parproduct_sum_reg[11] (.CK (clk), .D (n_14), .Q
       (Parproduct_sum[11]));
  DFFQX1 \Parproduct_sum_reg[12] (.CK (clk), .D (n_13), .Q
       (Parproduct_sum[12]));
  DFFQX1 \Parproduct_sum_reg[13] (.CK (clk), .D (n_11), .Q
       (Parproduct_sum[13]));
  DFFQX1 \Parproduct_sum_reg[14] (.CK (clk), .D (n_10), .Q
       (Parproduct_sum[14]));
  DFFQX1 \Parproduct_sum_reg[15] (.CK (clk), .D (n_9), .Q
       (Parproduct_sum[15]));
  DFFQX1 \Parproduct_sum_reg[16] (.CK (clk), .D (n_8), .Q
       (Parproduct_sum[16]));
  DFFQX1 \Parproduct_sum_reg[17] (.CK (clk), .D (n_7), .Q
       (Parproduct_sum[17]));
  DFFQX1 \Parproduct_sum_reg[18] (.CK (clk), .D (n_6), .Q
       (Parproduct_sum[18]));
  DFFQX1 \Parproduct_sum_reg[10] (.CK (clk), .D (n_12), .Q
       (Parproduct_sum[10]));
  DFFQX1 \Parproduct_sum_reg[20] (.CK (clk), .D (n_4), .Q
       (Parproduct_sum[20]));
  DFFQX1 \Parproduct_sum_reg[21] (.CK (clk), .D (n_15), .Q
       (Parproduct_sum[21]));
  DFFQX1 \Parproduct_sum_reg[22] (.CK (clk), .D (n_2), .Q
       (Parproduct_sum[22]));
  DFFQX1 \Parproduct_sum_reg[23] (.CK (clk), .D (n_1), .Q
       (Parproduct_sum[23]));
  DFFQX1 \Parproduct_sum_reg[24] (.CK (clk), .D (n_0), .Q
       (Parproduct_sum[24]));
  OAI21X1 g1780__1617(.A0 (n_198), .A1 (n_74), .B0 (n_199), .Y (n_36));
  AOI21XL g1781__2802(.A0 (n_197), .A1 (n_196), .B0 (rst), .Y (n_35));
  AOI21XL g1782__1705(.A0 (count[2]), .A1 (n_74), .B0 (n_25), .Y
       (n_34));
  NOR2BX1 g1783__5122(.AN (n_267), .B (rst), .Y (n_33));
  NOR2BX1 g1784__8246(.AN (n_270), .B (rst), .Y (n_32));
  NOR2BX1 g1785__7098(.AN (n_269), .B (rst), .Y (n_31));
  NOR2BX1 g1786__6131(.AN (n_268), .B (rst), .Y (n_30));
  NOR2BX1 g1787__1881(.AN (n_295), .B (rst), .Y (n_29));
  NOR2BX1 g1788__5115(.AN (n_266), .B (rst), .Y (n_28));
  NOR2BX1 g1789__7482(.AN (n_265), .B (rst), .Y (n_27));
  NOR2XL g1790__4733(.A (count[0]), .B (rst), .Y (n_26));
  NOR2XL g1791__6161(.A (count[2]), .B (n_74), .Y (n_25));
  NOR2BX1 g1792__9315(.AN (n_294), .B (rst), .Y (n_24));
  NOR2BX1 g1793__9945(.AN (n_293), .B (rst), .Y (n_23));
  NOR2BX1 g1794__2883(.AN (n_292), .B (rst), .Y (n_22));
  NOR2BX1 g1795__2346(.AN (n_296), .B (rst), .Y (n_21));
  NOR2BX1 g1796__1666(.AN (n_291), .B (rst), .Y (n_20));
  NOR2BX1 g1797__7410(.AN (n_290), .B (rst), .Y (n_19));
  NOR2BX1 g1798__6417(.AN (n_289), .B (rst), .Y (n_18));
  NOR2BX1 g1799__5477(.AN (n_288), .B (rst), .Y (n_17));
  NOR2BX1 g1800__2398(.AN (n_287), .B (rst), .Y (n_16));
  NOR2BX1 g1801__5107(.AN (n_275), .B (rst), .Y (n_15));
  NOR2BX1 g1802__6260(.AN (n_285), .B (rst), .Y (n_14));
  NOR2BX1 g1803__4319(.AN (n_284), .B (rst), .Y (n_13));
  NOR2BX1 g1804__8428(.AN (n_286), .B (rst), .Y (n_12));
  NOR2BX1 g1805__5526(.AN (n_283), .B (rst), .Y (n_11));
  NOR2BX1 g1806__6783(.AN (n_282), .B (rst), .Y (n_10));
  NOR2BX1 g1807__3680(.AN (n_281), .B (rst), .Y (n_9));
  NOR2BX1 g1808__1617(.AN (n_280), .B (rst), .Y (n_8));
  NOR2BX1 g1809__2802(.AN (n_279), .B (rst), .Y (n_7));
  NOR2BX1 g1810__1705(.AN (n_278), .B (rst), .Y (n_6));
  NOR2BX1 g1811__5122(.AN (n_277), .B (rst), .Y (n_5));
  NOR2BX1 g1812__8246(.AN (n_276), .B (rst), .Y (n_4));
  NOR2BX1 g1813__7098(.AN (n_271), .B (rst), .Y (n_3));
  NOR2BX1 g1814__6131(.AN (n_274), .B (rst), .Y (n_2));
  NOR2BX1 g1815__1881(.AN (n_273), .B (rst), .Y (n_1));
  NOR2BX1 g1816__5115(.AN (n_272), .B (rst), .Y (n_0));
  CLKXOR2X1 add_33_42_g748__7482(.A (Parproduct_sum[31]), .B
       (add_33_42_n_87), .Y (n_265));
  ADDFX1 add_33_42_g749__4733(.A (n_231), .B (Parproduct_sum[30]), .CI
       (add_33_42_n_85), .CO (add_33_42_n_87), .S (n_266));
  ADDFX1 add_33_42_g750__6161(.A (n_230), .B (Parproduct_sum[29]), .CI
       (add_33_42_n_83), .CO (add_33_42_n_85), .S (n_267));
  ADDFX1 add_33_42_g751__9315(.A (n_229), .B (Parproduct_sum[28]), .CI
       (add_33_42_n_81), .CO (add_33_42_n_83), .S (n_268));
  ADDFX1 add_33_42_g752__9945(.A (n_228), .B (Parproduct_sum[27]), .CI
       (add_33_42_n_79), .CO (add_33_42_n_81), .S (n_269));
  ADDFX1 add_33_42_g753__2883(.A (n_227), .B (Parproduct_sum[26]), .CI
       (add_33_42_n_77), .CO (add_33_42_n_79), .S (n_270));
  ADDFX1 add_33_42_g754__2346(.A (n_226), .B (Parproduct_sum[25]), .CI
       (add_33_42_n_75), .CO (add_33_42_n_77), .S (n_271));
  ADDFX1 add_33_42_g755__1666(.A (n_225), .B (Parproduct_sum[24]), .CI
       (add_33_42_n_73), .CO (add_33_42_n_75), .S (n_272));
  ADDFX1 add_33_42_g756__7410(.A (n_224), .B (Parproduct_sum[23]), .CI
       (add_33_42_n_71), .CO (add_33_42_n_73), .S (n_273));
  ADDFX1 add_33_42_g757__6417(.A (n_223), .B (Parproduct_sum[22]), .CI
       (add_33_42_n_69), .CO (add_33_42_n_71), .S (n_274));
  ADDFX1 add_33_42_g758__5477(.A (n_222), .B (Parproduct_sum[21]), .CI
       (add_33_42_n_67), .CO (add_33_42_n_69), .S (n_275));
  ADDFX1 add_33_42_g759__2398(.A (n_221), .B (Parproduct_sum[20]), .CI
       (add_33_42_n_65), .CO (add_33_42_n_67), .S (n_276));
  ADDFX1 add_33_42_g760__5107(.A (n_220), .B (Parproduct_sum[19]), .CI
       (add_33_42_n_63), .CO (add_33_42_n_65), .S (n_277));
  ADDFX1 add_33_42_g761__6260(.A (n_219), .B (Parproduct_sum[18]), .CI
       (add_33_42_n_61), .CO (add_33_42_n_63), .S (n_278));
  ADDFX1 add_33_42_g762__4319(.A (n_218), .B (Parproduct_sum[17]), .CI
       (add_33_42_n_59), .CO (add_33_42_n_61), .S (n_279));
  ADDFX1 add_33_42_g763__8428(.A (n_217), .B (Parproduct_sum[16]), .CI
       (add_33_42_n_57), .CO (add_33_42_n_59), .S (n_280));
  ADDFX1 add_33_42_g764__5526(.A (n_216), .B (Parproduct_sum[15]), .CI
       (add_33_42_n_55), .CO (add_33_42_n_57), .S (n_281));
  ADDFX1 add_33_42_g765__6783(.A (n_215), .B (Parproduct_sum[14]), .CI
       (add_33_42_n_53), .CO (add_33_42_n_55), .S (n_282));
  ADDFX1 add_33_42_g766__3680(.A (n_214), .B (Parproduct_sum[13]), .CI
       (add_33_42_n_51), .CO (add_33_42_n_53), .S (n_283));
  ADDFHX1 add_33_42_g767__1617(.A (n_213), .B (Parproduct_sum[12]), .CI
       (add_33_42_n_49), .CO (add_33_42_n_51), .S (n_284));
  ADDFHX1 add_33_42_g768__2802(.A (n_212), .B (Parproduct_sum[11]), .CI
       (add_33_42_n_48), .CO (add_33_42_n_49), .S (n_285));
  OAI2BB1X1 add_33_42_g769__1705(.A0N (Parproduct_sum[10]), .A1N
       (n_211), .B0 (add_33_42_n_46), .Y (add_33_42_n_48));
  CLKXOR2X1 add_33_42_g770__5122(.A (add_33_42_n_21), .B
       (add_33_42_n_45), .Y (n_286));
  OAI21X1 add_33_42_g771__8246(.A0 (Parproduct_sum[10]), .A1 (n_211),
       .B0 (add_33_42_n_45), .Y (add_33_42_n_46));
  OAI2BB1X1 add_33_42_g772__7098(.A0N (Parproduct_sum[9]), .A1N
       (n_210), .B0 (add_33_42_n_43), .Y (add_33_42_n_45));
  CLKXOR2X1 add_33_42_g773__6131(.A (add_33_42_n_20), .B
       (add_33_42_n_42), .Y (n_287));
  OAI21X1 add_33_42_g774__1881(.A0 (Parproduct_sum[9]), .A1 (n_210),
       .B0 (add_33_42_n_42), .Y (add_33_42_n_43));
  OAI2BB1X1 add_33_42_g775__5115(.A0N (Parproduct_sum[8]), .A1N
       (n_209), .B0 (add_33_42_n_40), .Y (add_33_42_n_42));
  CLKXOR2X1 add_33_42_g776__7482(.A (add_33_42_n_19), .B
       (add_33_42_n_39), .Y (n_288));
  OAI21X1 add_33_42_g777__4733(.A0 (Parproduct_sum[8]), .A1 (n_209),
       .B0 (add_33_42_n_39), .Y (add_33_42_n_40));
  OAI2BB1X1 add_33_42_g778__6161(.A0N (Parproduct_sum[7]), .A1N
       (n_208), .B0 (add_33_42_n_37), .Y (add_33_42_n_39));
  CLKXOR2X1 add_33_42_g779__9315(.A (add_33_42_n_18), .B
       (add_33_42_n_36), .Y (n_289));
  OAI21X1 add_33_42_g780__9945(.A0 (Parproduct_sum[7]), .A1 (n_208),
       .B0 (add_33_42_n_36), .Y (add_33_42_n_37));
  OAI21X2 add_33_42_g781__2883(.A0 (add_33_42_n_10), .A1
       (add_33_42_n_34), .B0 (add_33_42_n_4), .Y (add_33_42_n_36));
  MXI2XL add_33_42_g782__2346(.A (add_33_42_n_34), .B (add_33_42_n_33),
       .S0 (add_33_42_n_17), .Y (n_290));
  CLKINVX1 add_33_42_g783(.A (add_33_42_n_33), .Y (add_33_42_n_34));
  OAI21X1 add_33_42_g784__1666(.A0 (add_33_42_n_7), .A1
       (add_33_42_n_32), .B0 (add_33_42_n_2), .Y (add_33_42_n_33));
  AOI21X1 add_33_42_g787__7410(.A0 (add_33_42_n_6), .A1
       (add_33_42_n_30), .B0 (add_33_42_n_23), .Y (add_33_42_n_32));
  CLKXOR2X1 add_33_42_g788__6417(.A (add_33_42_n_24), .B
       (add_33_42_n_30), .Y (n_292));
  OAI21X2 add_33_42_g789__5477(.A0 (add_33_42_n_11), .A1
       (add_33_42_n_29), .B0 (add_33_42_n_3), .Y (add_33_42_n_30));
  AOI22X1 add_33_42_g792__2398(.A0 (add_33_42_n_8), .A1
       (add_33_42_n_27), .B0 (Parproduct_sum[2]), .B1 (n_203), .Y
       (add_33_42_n_29));
  CLKXOR2X1 add_33_42_g793__5107(.A (add_33_42_n_14), .B
       (add_33_42_n_27), .Y (n_294));
  OAI21X1 add_33_42_g794__6260(.A0 (add_33_42_n_9), .A1
       (add_33_42_n_12), .B0 (add_33_42_n_5), .Y (add_33_42_n_27));
  OAI21X1 add_33_42_g795__4319(.A0 (add_33_42_n_12), .A1
       (add_33_42_n_13), .B0 (add_33_42_n_25), .Y (n_295));
  NAND2XL add_33_42_g796__8428(.A (add_33_42_n_12), .B
       (add_33_42_n_13), .Y (add_33_42_n_25));
  ADDHX1 add_33_42_g797__5526(.A (Parproduct_sum[4]), .B (n_205), .CO
       (add_33_42_n_23), .S (add_33_42_n_24));
  OA21XL add_33_42_g798__6783(.A0 (Parproduct_sum[0]), .A1 (n_201), .B0
       (add_33_42_n_12), .Y (n_296));
  XOR2XL add_33_42_g799__3680(.A (Parproduct_sum[10]), .B (n_211), .Y
       (add_33_42_n_21));
  XOR2XL add_33_42_g800__1617(.A (Parproduct_sum[9]), .B (n_210), .Y
       (add_33_42_n_20));
  XOR2XL add_33_42_g801__2802(.A (Parproduct_sum[8]), .B (n_209), .Y
       (add_33_42_n_19));
  XOR2XL add_33_42_g802__1705(.A (Parproduct_sum[7]), .B (n_208), .Y
       (add_33_42_n_18));
  CLKXOR2X1 add_33_42_g803__5122(.A (Parproduct_sum[6]), .B (n_207), .Y
       (add_33_42_n_17));
  CLKXOR2X1 add_33_42_g804__8246(.A (Parproduct_sum[5]), .B (n_206), .Y
       (add_33_42_n_16));
  CLKXOR2X1 add_33_42_g805__7098(.A (Parproduct_sum[3]), .B (n_204), .Y
       (add_33_42_n_15));
  XOR2XL add_33_42_g806__6131(.A (Parproduct_sum[2]), .B (n_203), .Y
       (add_33_42_n_14));
  CLKXOR2X1 add_33_42_g807__1881(.A (Parproduct_sum[1]), .B (n_202), .Y
       (add_33_42_n_13));
  NOR2XL add_33_42_g808__5115(.A (Parproduct_sum[3]), .B (n_204), .Y
       (add_33_42_n_11));
  NOR2XL add_33_42_g809__7482(.A (Parproduct_sum[6]), .B (n_207), .Y
       (add_33_42_n_10));
  NOR2XL add_33_42_g810__4733(.A (Parproduct_sum[1]), .B (n_202), .Y
       (add_33_42_n_9));
  OR2X1 add_33_42_g811__6161(.A (Parproduct_sum[2]), .B (n_203), .Y
       (add_33_42_n_8));
  NAND2XL add_33_42_g812__9315(.A (n_201), .B (Parproduct_sum[0]), .Y
       (add_33_42_n_12));
  NOR2XL add_33_42_g813__9945(.A (Parproduct_sum[5]), .B (n_206), .Y
       (add_33_42_n_7));
  OR2XL add_33_42_g814__2883(.A (Parproduct_sum[4]), .B (n_205), .Y
       (add_33_42_n_6));
  NAND2XL add_33_42_g815__2346(.A (Parproduct_sum[1]), .B (n_202), .Y
       (add_33_42_n_5));
  NAND2XL add_33_42_g816__1666(.A (Parproduct_sum[6]), .B (n_207), .Y
       (add_33_42_n_4));
  NAND2XL add_33_42_g817__7410(.A (Parproduct_sum[3]), .B (n_204), .Y
       (add_33_42_n_3));
  NAND2XL add_33_42_g818__6417(.A (Parproduct_sum[5]), .B (n_206), .Y
       (add_33_42_n_2));
  XNOR2XL add_33_42_g2__5477(.A (add_33_42_n_32), .B (add_33_42_n_16),
       .Y (n_291));
  XNOR2XL add_33_42_g819__2398(.A (add_33_42_n_29), .B
       (add_33_42_n_15), .Y (n_293));
  DFFX1 \count_reg[3] (.CK (clk), .D (n_39), .Q (count[3]), .QN (n_52));
  NOR4BX4 g2(.AN (n_133), .B (n_300), .C (n_309), .D (n_135), .Y
       (n_298));
  OAI2BB1X1 g3926(.A0N (n_50), .A1N (Serial_multin2[2]), .B0 (n_304),
       .Y (n_299));
  OAI2BB1X1 g3927(.A0N (n_49), .A1N (Serial_multin2[10]), .B0 (n_306),
       .Y (n_300));
  OAI2BB1X2 g3928(.A0N (n_47), .A1N (Serial_multin2[14]), .B0 (n_303),
       .Y (n_301));
  OAI2BB1X4 g3929(.A0N (n_48), .A1N (Serial_multin2[6]), .B0 (n_119),
       .Y (n_302));
  NAND3X1 g3930(.A (n_72), .B (n_59), .C (Serial_multin2[15]), .Y
       (n_303));
  NAND3X1 g3931(.A (n_59), .B (n_58), .C (Serial_multin2[3]), .Y
       (n_304));
  NAND3X1 g3932(.A (n_71), .B (n_75), .C (Serial_multin2[5]), .Y
       (n_305));
  NAND3X1 g3933(.A (n_70), .B (n_75), .C (Serial_multin2[9]), .Y
       (n_306));
  NAND3X1 g3934(.A (n_75), .B (n_58), .C (Serial_multin2[1]), .Y
       (n_307));
  OAI2BB1X2 g3935(.A0N (n_107), .A1N (Serial_multin2[11]), .B0 (n_308),
       .Y (n_309));
  NAND3X1 g3(.A (n_76), .B (n_70), .C (Serial_multin2[8]), .Y (n_308));
  OAI2BB1X1 g3936(.A0N (n_106), .A1N (Serial_multin2[13]), .B0 (n_310),
       .Y (n_311));
  NAND3X1 g3937(.A (n_72), .B (n_76), .C (Serial_multin2[12]), .Y
       (n_310));
endmodule

